### ISSUE TITLE
Icon in Toast on Mobile is misaligned when the text is one line

### ISSUE THREAD

**Issue by Danieljs-codes** [justdlabs/justd#197]
**Describe the bug**
The Icon on the Toast on mobile is misaligned if the text is just one line but if it is two it aligns pretty well
**To Reproduce**
1. Go to '[JustD](https://getjustd.com/docs/components/statuses/toast)'
2. Scroll down to 'Status.'
3. Click on 'Each Toast'
4. See the issue (on Mobile)

**Comment by irsyadadl** [comment]
Thanks for let me know. Will fix in the next update.

**Comment by irsyadadl** [comment]
This issue is been resolve on #198
