### ISSUE TITLE
For dialogs and the components using it, it triggers a typescript error

### ISSUE THREAD

**Issue by Itsnotaka** [justdlabs/justd#201]
**Describe the bug**
The Error that is being triggered is being described by this StackOverflow thread https://stackoverflow.com/questions/43900035/ts4023-exported-variable-x-has-or-is-using-name-y-from-external-module-but
The error shows on two components that extends the prop, Header and Title.

**Expected behavior**
No error should be shown when using Modal, Sheets 

**Additional context**
The problem can be fixed by using `type` instead of `interface`, I honestly have no idea why this is not fixed by TS yet.

**Comment by irsyadadl** [comment]
It shoud be fix on the #[5eb4e92](https://github.com/justdlabs/justd/commit/5eb4e92c1da66341b0a8bd16e78c644261e16b70)

**Comment by Itsnotaka** [comment]
I suggest also change the `DialogTitleProp` as well

**Comment by irsyadadl** [comment]
Can you make a pr. I've close my laptop actually. If you don't, never mind. I'll do it tomorrow.

**Comment by irsyadadl** [comment]
Thanks. Merged #202
