### ISSUE TITLE
Adding Column Resizing to the Table component 

### ISSUE THREAD

**Issue by MikeBurkeMed** [justdlabs/justd#208]
**Is your feature request related to a problem? Please describe.**
A common feature that is often overlooked in libraries is that they don't have column resizing capablities in table components and often, it takes a lot of time to implement it with external dependencies. It would be amazing to add support for column resizing out of the box. 

**Describe the solution you'd like**
Having column resizing on table components

**Describe alternatives you've considered**
External libs such as tanstack table can handle it but it's always clunky and does not fit into the tables out of the box and major modifications becomes necessary

**Additional context**
Cloudscape has implemented this very nicely:

https://cloudscape.design/components/table/?tabId=playground&example=resizable-columns

Maybe we can be inspired by them to implement similar functionality.

**Comment by irsyadadl** [comment]
Yeah. Infact RAC has featured on that. If we can make it to be optional like putting the props to the Table like allowResizing would be cold.

**Comment by irsyadadl** [comment]
It's called ResizableTableContainer. Do you plan to make a PR?

**Comment by MikeBurkeMed** [comment]
Hi @irsyadadl that would indeed be awesome and sure, this week I'm a little busy with work, but if no one has done by next week, I'll make a PR.

**Comment by irsyadadl** [comment]
I've just added the `allowResize` to table props. So it's fixed now. [new featured: allow resize to the table](https://github.com/justdlabs/justd/commit/a12de2a2ea59772d3bdeebcc946dfcbd384bebfb)
