### ISSUE TITLE
Documentation for Toast Component rendered twice

### ISSUE THREAD

**Issue by Deri-Kurniawan** [justdlabs/justd#209]
**Describe the bug**
When the button to display toast is clicked on the component documentation page. There are two toast that appear, and they are more obvious when the toast is closed.

All toasts on the page are rendered twice.

**To Reproduce**
1. Go to [Toast Component Documentation](https://getjustd.com/docs/components/statuses/toast)
2. Click on "Show Toast" button
3. See toast rendered twice (clearer when closed)

**Expected behavior**
It should only be one that appears, if two like that I assume that the component is problematic, it turns out that it is only in the documentation.

**Screenshots**
You can see it more clearly here [Jam bug report](https://jam.dev/c/1b3fdd26-67d4-468b-a3e6-f3953a5fce77)

**Desktop (please complete the following information):**
 - Browser Brave
 - Browser Firefox Developer Edition

**Smartphone (please complete the following information):**
none

**Additional context**
none

**Comment by irsyadadl** [comment]
Solved in [25a9089](https://github.com/justdlabs/justd/commit/25a9089261c02975cf1fcf89ecc42de0399822d3)
