### ISSUE TITLE
Minor Bug in Newly released themes

### ISSUE THREAD

**Issue by Danieljs-codes** [justdlabs/justd#211]
**Describe the bug**
I saw your post on twitter about the new themes features and I decided to try out the new zinc theme which is absolutely amazing the generated CSS has an Issue the styling for scrollbar looks like this

![image](https://github.com/user-attachments/assets/f694a412-ae83-457e-9fc3-d8581153fe9c)
When they  should look more like this
![image](https://github.com/user-attachments/assets/e4fa0097-4d22-4985-b072-9b2ddc60f74a)

The colors should be wrapped in `oklch`

**Comment by irsyadadl** [comment]
Ah got it. Thanks for the report. Will patch it in the next release ASAP.
