### ISSUE TITLE
Sidebar collapse issue

### ISSUE THREAD

**Issue by shaikahmadnawaz** [justdlabs/justd#212]
Even after navigating to next section I cant see the opening of the sidebar of the present section and previous section haven't collapsed yet.

![image](https://github.com/user-attachments/assets/b1b7cd45-01f5-49af-aaf8-e9b95d8af5a1)

I opened it manually from sidebar.

![image](https://github.com/user-attachments/assets/60bb2d59-f772-4e09-b84b-2bd4d0fa773d)

When I navigate to next section the previous section in the sidebar has to collapse automatically and the next section has to open.

**Desktop:**
 - Arc

**Comment by irsyadadl** [comment]
Post issue if this related to the core components. Otherwise please use discussion!

**Comment by shaikahmadnawaz** [comment]
> Post issue if this related to the core components. Otherwise please use discussion!

Okay 👍
