### ISSUE TITLE
Selection of year and month in Date Picker

### ISSUE THREAD

**Issue by shaikahmadnawaz** [justdlabs/justd#213]
In date picker is it possible to select year and month manually like date.

![image](https://github.com/user-attachments/assets/9302780e-5b1a-4833-9368-42691e72d0a7)

For suppose I want to select the 2000 year, it will be very hard for me to click that many times.

Hope you will understand.

**Comment by yuxxeun** [comment]
In fact, you can type the year and month (even date too) manually in the input section

![image](https://github.com/user-attachments/assets/90e2d0fa-5336-42e0-934b-3f787a47fb16)

**Comment by irsyadadl** [comment]
We don't make it as plan at least right now.

**Comment by shaikahmadnawaz** [comment]
> We don't make it as plan at least right now.

Okay!
