### ISSUE TITLE
Scrollable on Tabs component

### ISSUE THREAD

**Issue by yuxxeun** [justdlabs/justd#215]
It is possible to show scrollbar on `tabs` component when its has overflow? just like `table` component.
For example, I've use `tabs` component with many tab lists and the tab is overflowing

![image](https://github.com/user-attachments/assets/548f66ec-e04d-4e93-ac02-80f2f961aec4)

**Comment by irsyadadl** [comment]
Tabs can be vertical and horizontal, when you're on small screen. You should never use horizontal mode, instead vertical.

**Comment by yuxxeun** [comment]
still overflow when I user `orientation="vertical"`

![image](https://github.com/user-attachments/assets/30e9a623-fca5-4daa-a6ef-cd42d80b26d8)

**Comment by irsyadadl** [comment]
Then use something else like [docs](https://getjustd.com/docs/components/navigation/tabs) offer.
