### ISSUE TITLE
Width on Aside component

### ISSUE THREAD

**Issue by yuxxeun** [justdlabs/justd#220]
I don't know it is by-design or need _enhancement_.

I just realize there's an `margin` on `Aside` component on default browser size (`100%`)

![image](https://github.com/user-attachments/assets/77e221c6-3ae9-46cd-a6a6-49e092422822)

Then I'm trying to fix it on my personal project that build with it:

![image](https://github.com/user-attachments/assets/60074d1e-25d0-4f89-8a4d-2f948bdcd6c2)

If its by-design, its ok I wouldn't make PR, but if its should be fixed let me make pull request

**Comment by irsyadadl** [comment]
Can you please take the latest version from aside, because before this issue it has been changed a lot.

**Comment by yuxxeun** [comment]
using the latest version, now it fixed after copied the whole code from JustD source (which is remove the `layout` property from `slot` object), nice!

![image](https://github.com/user-attachments/assets/476938e3-e75c-4ac5-bc09-16f5083efcc3)
