### ISSUE TITLE
Feature request: Tree Select

### ISSUE THREAD

**Issue by kurumeii** [justdlabs/justd#230]
It would be fantastic if this awesome ui library included a tree select. I have been looking for this component everywhere, and only a few have it, but their style does not give me the same modern look as yours. I really hope that you can implement this.

**Comment by irsyadadl** [comment]
Give example of tree select you meant!

**Comment by kurumeii** [comment]
Oh, sure thing !
Something like antd would do, here is the [example](https://ant.design/components/tree-select).
