### ISSUE TITLE
Sidebar no longer opens between 601 and 767px wide

### ISSUE THREAD

**Issue by t-rosa** [justdlabs/justd#235]
**Describe the bug**
The sidebar no longer opens between 601 and 767px wide.

**To Reproduce**
1. Go to [https://getjustd.com/blocks/sidebar/sidebar-01](https://getjustd.com/blocks/sidebar/sidebar-01)
2. Open the devtools
3. Activate the device emulation
4. In reactive mode, set the window width to a number between 600 and 768
![image](https://github.com/user-attachments/assets/92bf879c-8afd-4af0-9fe4-3005108d49de)
5. Try to toggle the sidebar

**Comment by irsyadadl** [comment]
I will checkout this bug. And will fix 2 hours from now.

**Comment by t-rosa** [comment]
Thank you!

**Comment by irsyadadl** [comment]
It has been fixed on [b0ba246](https://github.com/justdlabs/justd/commit/424d4ecad8b28e6f25bfd715b595386b5c7926f9)
